FROM maven:3.6.3-jdk-11 AS builder
ENV PROFILE=prod
WORKDIR /opt/app
COPY . .
RUN mvn package

FROM registry.access.redhat.com/ubi8/openjdk-11
ENV COMPONENT_CATALOG_HOST=catalog-spring-boot
ENV COMPONENT_CATALOG_PORT=8080
ENV COMPONENT_INVENTORY_HOST=inventory-quarkus
ENV COMPONENT_INVENTORY_PORT=8080
COPY --from=builder /opt/app/target/*.jar /app.jar
CMD java -jar /app.jar -Dhttp.port=8080
EXPOSE 8080
